# Generated by Django 5.1.3 on 2024-11-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='ai_analysis',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='safety_tips',
            field=models.TextField(null=True),
        ),
    ]
