# Generated by Django 5.1.3 on 2024-11-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_alert_options_alter_emergencycontact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='priority_level',
            field=models.CharField(default='High', max_length=10),
        ),
    ]
